server:
  port: 6060
  request:
    maxBodySize: 2048mb
    maxHeaderSize: 20mb
  
project:
  sqlPrint: false
  beanPackage: com.cym.model
  home: /home/svnWebUI/
  findPass: false
  
solon:
  app.name: svnWebUI
  view.mapping.html: FreemarkerRender
  logging:
    "io.undertow":
        level: "WARN"
    appender:
      file:
        name: ${project.home}/log/${solon.app.name}
        level: INFO
        maxFileSize: "100 MB"
        maxHistory: "7"
database:
  type: h2
  url: 
  username: 
  password: 
  