server:
  port: 6060
  servlet: 
    session:
      timeout: 7200 
  tomcat:
    threads:
      max: 5 #减少tomcat线程数
      
spring:
  application:
    name: svnWebUI
  devtools:
    restart:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL
  jmx:
    enabled: true 
  database: 
    type: sqlite
    package: com.cym.model
    print: false
    sqlite-path: ${project.home}sqlite.db

project:
  version: v@project.version@
  home: /home/svnWebUI/

logging: 
  file:
    name: ${project.home}log/svnWebUI.log
    max-size: 1024MB
  level: 
    root: info